version: "2"
services:
  zookeeper:
    hostname: zookeeper
    build:
      context: ./zookeeper/
  kafka:
    hostname: kafka
    build:
      context: ./kafka/
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
  init:
    hostname: init
    build:
      context: ./init/
    depends_on:
      - zookeeper
      - kafka