version: "3"
services:
  zookeeper:
    hostname: zookeeper
    build:
      context: ./zookeeper/
  kafka:
    hostname: kafka
    build:
      context: ./kafka/
    depends_on:
      - zookeeper
      - opa
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - CLASSPATH=/usr/local/share/kafka/plugins/*
  opa:
    hostname: opa
    build:
      context: ./opa/
    ports:
      - 8181:8181
